### ISSUE TITLE
Blog - # of cards

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pcc#107]
**Is your feature request related to a problem? Please describe.**
6 blog posts makes a pretty short page with a lot of clicking to get to the next pages... what do you think of having either 9 or 12 tiles?

**Comment by greatislander** [comment]
This is in WordPress Settings. I changed it to 9, but we can change it more if needed.

![Reading settings.](https://user-images.githubusercontent.com/605361/64447421-97afd480-d098-11e9-93c5-cd8f6f44be23.png)
