### ISSUE TITLE
Blog - spacing inside & between cards

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pcc#109]
**Is your feature request related to a problem? Please describe.**
I noticed that currently, if there are cards that have different length titles next to each other, it ends up adjusting to the height of the card with the longest title:

![Screen Shot 2019-09-06 at 11 55 18 AM](https://user-images.githubusercontent.com/9353905/64442459-d6945900-d09d-11e9-912e-7fef8e3dcda2.png)

This creates a bit of excessive white space inside cards that have shorter titles.

**Describe the solution you'd like**
What might the page look like if the card height was custom to the length of their title? I guess the page might end up looking kind of like Pinterest?

<img width="1057" alt="Screen Shot 2019-09-06 at 12 00 40 PM" src="https://user-images.githubusercontent.com/9353905/64442543-fa579f00-d09d-11e9-99fe-0e1a1660346f.png">

**Describe alternatives you've considered**
Alternatively, we could try having a max line length / character count on the titles - maybe 3 or 4 lines?

**Comment by greatislander** [comment]
We should be enforcing a max line length/character count; this also benefits SEO.
