### ISSUE TITLE
Blog - video not fully scaled to mobile viewport

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pcc#111]
**Is your feature request related to a problem? Please describe.**
It seems like on mobile, the width of youtube videos don't fully fit in the viewport:

![Screen Shot 2019-09-06 at 12 04 14 PM](https://user-images.githubusercontent.com/9353905/64442969-e1032280-d09e-11e9-9a57-a73a194dda9a.png)

**Describe the solution you'd like**
Is it possible to fit it into the screen?

**Comment by greatislander** [comment]
Fixed for YouTube by embedding them properly; implemented temporary fix for LiveStream and Archive.org embeds.
