### ISSUE TITLE
Creating Conference Program 

### ISSUE THREAD

**Issue by Trebors2** [platform-coop-toolkit/pcc#142]
**Describe the bug**

Not a bug. I don't know how to create the conference program on the website. I searched but could not find the functionality.  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by greatislander** [comment]
@Trebors2 Events in the program are events just like the conference itself. You just need to set the "Parent" to the conference to get them to show up on the program page:

<img width="279" alt="Parent" src="https://user-images.githubusercontent.com/605361/65380655-0a29d280-dc9d-11e9-80c0-7f7bee667134.png">
