### ISSUE TITLE
Add RSS feed for blog posts

### ISSUE THREAD

**Issue by difea451** [platform-coop-toolkit/pcc#231]
## Is your feature request related to a problem? Please describe.

We have received feedback that visitors to the PCC Website would like an RSS Feed for the Blog posts on the blog section of the website

## Describe the solution you'd like
RSS capability/integration of https://platform.coop/voices/blog/

**Comment by greatislander** [comment]
Hi @difea451, there is already an RSS feed. I'm able to subscribe to it by adding https://platform.coop to my RSS reader (the feed is https://platform.coop/feed/ and is detected automatically).

**Comment by greatislander** [comment]
@difea451 I'm closing this as I haven't had a response since last week but please let me know if you need anything else.

**Comment by difea451** [comment]
Sorry Ned- 
I passed your response on to Trebor, and he never said anything in reply so I assume he has received and absorbed it. Thanks for the response on it. I don't think anybody was looking for any additional functionality, I think it was just...user error...

**Comment by greatislander** [comment]
Okay, no problem. Thanks Angela.
