### ISSUE TITLE
QA-Home page: Donate spacing

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pcc#43]
![Screen Shot 2019-07-05 at 4 14 35 PM](https://user-images.githubusercontent.com/9353905/60743671-9ea75300-9f40-11e9-9f63-22645c291edc.png)

Can the space between "donate" to the bottom of the photo, be the same as the space between the "donate now" button and the bottom of the module? The bottom space looks a bit taller than the top space.

**Comment by greatislander** [comment]
If preceded by image + text block, add extra margin.
