### ISSUE TITLE
Improve breadcrumb layout on mobile

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pcc#55]
![Screen Shot 2019-07-05 at 4 41 44 PM](https://user-images.githubusercontent.com/9353905/60744807-86860280-9f45-11e9-82c1-eff71c46549a.png)

Splits into 2 lines awkwardly... any way to cut off whatever doesn't fit into the first line with a "..."? Ex. "<Back to how platform co-ops can..."

**Comment by greatislander** [comment]
Idea, @cherylhjli: since the backwards chevron indicates "Back to", can we shorten the text on these to the name of the target page? So it would be:

```
‹ How Platform Co-ops Can Benefit You
```

We could include "Back to" as visually hidden text for screen readers. Thoughts @jhung?

**Comment by cherylhjli** [comment]
works for me
