### ISSUE TITLE
QA-Contact us: Send us a message

### ISSUE THREAD

**Issue by cherylhjli** [platform-coop-toolkit/pcc#57]
![66060623_357068258312777_2345738702728200192_n](https://user-images.githubusercontent.com/9353905/60745963-86d4cc80-9f4a-11e9-85f1-01c5665f23c8.jpg)

This is a screenshot on my phone, and I just noticed a few things..
- the send message button is this odd rounded one! 
- the "name" is running into the line above a little bit - could it have the same spae as the space between the bottom of the name text field, and the top of "email"?

**Comment by greatislander** [comment]
Spacing is fixed now. Will investigate the button!
