### ISSUE TITLE
Add People page

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/pcc#84]

**Comment by cherylhjli** [comment]
Desktop & mobile screens & specs: https://xd.adobe.com/spec/183bfcc0-3e02-4b8c-5d56-f3a11fcd7071-6e0a/grid/

**Comment by cherylhjli** [comment]
I've added some interactions between desktop and mobile view - they are not accurate, they're just to connect the screens so they all show up in the speccing software.
